// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import { readFileSync, existsSync } from 'node:fs';

// ─── Conditional Keystatic CMS ──────────────────────────────────────
// Enable with: KEYSTATIC=true npm run dev  (local editing only)
// Production builds are always static — Keystatic is a local dev tool.
const isKeystatic = process.env.KEYSTATIC === 'true';

let keystatic, node;
if (isKeystatic) {
  keystatic = (await import('@keystatic/astro')).default;
  node = (await import('@astrojs/node')).default;
}

// ─── Redirects ───────────────────────────────────────────────────────
// All URL redirects are handled server-side via Apache .htaccess rules
// generated by `node cli/migrate.js` into astro-theme/public/.htaccess.
// Astro's own `redirects:` config is intentionally NOT used here because
// in static output mode it generates HTML pages with a visible
// "Redirecting to: /path" text before navigation — which is the exact
// client-side flash the client reported.  .htaccess 301s are transparent.

// ─── Site URL from site-config.json ─────────────────────────────────
let siteUrl = 'https://example.ch';
try {
  if (existsSync('./src/content/site-config.json')) {
    const cfg = JSON.parse(readFileSync('./src/content/site-config.json', 'utf-8'));
    if (cfg.siteUrl) siteUrl = cfg.siteUrl;
  }
} catch {}

// https://astro.build/config
export default defineConfig({
  site: siteUrl,
  output: isKeystatic ? 'server' : 'static',
  adapter: isKeystatic ? node({ mode: 'standalone' }) : undefined,
  integrations: [
    sitemap(),
    ...(isKeystatic && keystatic ? [keystatic()] : []),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});